Race factory tests
Codibre/remembered-redis pull request #17
Opened 2022-05-11 01:28 UTC by DanielM08

Isolate raceFactory function into a file and create its unit tests.

2022-05-11 01:50 UTC, Farenheith requested changes

2022-05-11 01:50 UTC, Farenheith commented on test/unit/get-redis-prefix.spec.ts
> +	it('should return prefix as is when an string is informed that ends with :', () => {
```suggestion
	it('should return prefix as is when a string is informed that ends with :', () => {
```

2022-05-11 01:50 UTC, Farenheith commented on test/unit/get-redis-prefix.spec.ts
> +	it('should return prefix followed by : when an string is informed that not ends in it', () => {
```suggestion
	it('should return prefix followed by : when a string is informed that not ends in it', () => {
```

2022-05-11 01:50 UTC, Farenheith commented on test/unit/race-factory.spec.ts
> +	it('should return a function that returns a rejected promise if the callback received as parameter do not finish before a specified timeout', async () => {
```suggestion
	it('should return a function that returns a rejected promise if the callback received as parameter does not finish before the specified timeout', async () => {
```

2022-05-11 01:50 UTC, Farenheith commented on test/unit/try-to-factory.spec.ts
> +	it('should return a function that runs the action and not log an error, if the action throws one and logError is undefined', async () => {
```suggestion
	it('should return a function that runs the action and do not log an error, if the action throws one and logError is undefined', async () => {
```

2022-05-11 01:50 UTC, Farenheith commented on test/unit/try-to-factory.spec.ts
> +	it('should return a function that runs the action and not log an error, if the action throws one and logError is undefined', async () => {
```suggestion
	it('should return a function that runs the action and do not log an error, if the action throws one and logError is undefined', async () => {
```

2022-05-11 02:07 UTC, Farenheith approved these changes

2022-05-11 12:45 UTC, Dodt approved these changes

2022-05-11 12:45 UTC, Dodt commented on src/race-factory.ts
> +				delay(timeout).then(() => {
I know that you are just using it, but to share some knowledge, you can use the setTimeout of 'timers/promises'; it is a lib native in node.js and is a promise, but I think for compatibility with older versions of node.js we can live like this :smile:

2022-05-12 00:55 UTC, Farenheith submitted a review, later dismissed

2022-05-12 01:33 UTC, Farenheith submitted a review, later dismissed

2022-05-12 10:54 UTC, Farenheith approved these changes

2022-05-17 13:08 UTC, gustavobeavis approved these changes
Nice refactored code; I have only one suggestion for the next time. 
You should use just one commit because in that case, you changed only one aspect of the code, and the tests, class change, and imports were done to resolve just one implementation of raceFacotry, because it bete use only one commit.

try to write verbose commits like this https://dhwthompson.com/2019/my-favourite-git-commit next time and use `git commit --amend `

2022-05-22 14:10 UTC, merged